<!-- Tabs -->	
<ul class="nav nav-pills nav-perso">
   <li class="li-doc2xml active"><a data-toggle="tab" href="#doc2xml"> <i class="fa fa-file-code-o"></i> Document to XML</a></li>
   <li class="li-xml2rdf"><a data-toggle="tab" href="#xml2rdf"><i class="fa fa-object-group"></i> Document to RDF</a></li>
</ul>

<div class="panel panel-default panel-upload">
	<div class="panel-body">
		
         <div>
     	 
         	 <input type="hidden" name="row_id" id="row_id"/>
	         <input type="hidden" name="selected_item_dc" id="selected_item_dc"/>
	         <input type="hidden" name="selected_item_tei" id="selected_item_tei"/>
	         <input type="hidden" name="selected_item_mpeg7-vd" id="selected_item_mpeg7-vd"/>
	         <input type="hidden" name="selected_item_linkedmdr" id="selected_item_linkedmdr"/>
	         
	         <!-- Tab content -->
	         
			 <div class="tab-content">
			    <div id="doc2xml" class="tab-pane fade in active">
			      <br>
			      <button type="button" class="add-file-2xml btn btn-success btn-sm "><i class="glyphicon glyphicon-plus" ></i> Add file</button>
			         <table class="table table-upload table-2xml table-striped">
					    <thead>
					      <tr class="info">
					      	<th>Selected File</th>
					        <th>File name</th>
					        <th><i class="fa fa-file-code-o"></i> Standards</th>
					        <th>Actions</th>
					      </tr>
					    </thead>
					    <tbody>
					     <!-- Td will be generated by upload.js-->
					    </tbody>
			         </table>
			   </div>
			   <div id="xml2rdf" class="tab-pane fade">
			    	<br>
			     	<button type="button" class="add-file-2rdf btn btn-success btn-sm "><i class="glyphicon glyphicon-plus" ></i> Add file</button>
			         <table class="table  table-upload table-2rdf table-striped">
					    <thead>
					      <tr class="info">
					      	<th>Selected File</th>
					        <th>File name</th>
					        <th><i class="fa fa-object-group"></i> LinkedMDR</th>
					        <th>Actions</th>
					      </tr>
					    </thead>
					    <tbody>
					     <!-- Td will be generated by upload.js-->
					    </tbody>
			         </table>
			   </div>
			 </div>		
         </div>
	</div>
</div>

