<div class="panel panel-default panel-upload">
	<div class="panel-heading"><i class="fa fa-upload"></i>  <strong>Upload files</strong> <small> </small></div>
	<div class="panel-body">
         <div>
         	 <p><b> Step 1 : </b> select the files you want to transform</p>
         	 <p><b> Step 2 : </b> select the transformation</p>
         	 <p><b> Step 3 : </b> download the file</p>
         	 
         	 <input type="hidden" name="row_id" id="row_id"/>
	         <input type="hidden" name="selected_item_dc" id="selected_item_dc"/>
	         <input type="hidden" name="selected_item_tei" id="selected_item_tei"/>
	         <input type="hidden" name="selected_item_mpeg7" id="selected_item_mpeg7"/>
	         <input type="hidden" name="selected_item_linkedmdr" id="selected_item_linkedmdr"/>
         	 
         	 <button type="button" class="add-file btn btn-success btn-sm "><i class="glyphicon glyphicon-plus" ></i> Add file</button>
	         <table class="table table-upload table-striped">
			    <thead>
			      <tr class="info">
			      	<th>Selected File</th>
			        <th>File name</th>
			        <th><i class="fa fa-file-code-o"></i> Transform to standard/Xml</th>
			        <th><i class="fa fa-object-group"></i> Transform to LinkedMDR/Rdf</th>
			        <th><i class="fa fa-object-group"></i> Multiple LinkedMDR</th>
			        <th>Actions</th>
			      </tr>
			    </thead>
			    <tbody>
			     <!-- Td will be generated by upload.js-->
			    </tbody>
	         </table>
	         <div class="text-center">
	         <button type="submit" class="btn btn-primary btn-md btn-linkedmdr" disabled>Download LinkedMDR</button>
	         </div>
         </div>
	</div>
	
</div>

