<!-- Tabs -->	
<ul class="nav nav-pills nav-perso">
   <li class="li-doc2xml active"><a data-toggle="tab" href="#doc2xml"> <i class="fa fa-file-code-o"></i> Document to XML</a></li>
   <li class="li-xml2rdf"><a data-toggle="tab" href="#xml2rdf"><i class="fa fa-object-group"></i> Document to RDF</a></li>
</ul>

<div class="panel panel-default panel-upload">
	<div class="panel-body">
		
         <div>
	         <!-- Tab content -->
	         
			 <div class="tab-content">
			 
			    <div id="doc2xml" class="tab-pane fade in active">
				      <br>
				  	<form action="SrvMain" method="post"  enctype="multipart/form-data">
				      	<div class='input-group input-file input-file-2xml'>
				    		 <label class='btn btn-sm btn-primary btn-upload'>
				    			Browse files...<input style='display: none;' class="input-file" name="filesToUpload[]" id="filesToUpload" type="file" accept=".jpg, .png, .jpeg, .docx, .pdf" multiple>
				    		 </label>
			    		 </div>
				         <table class="table table-upload table-2xml table-striped">
						    <thead>
						      <tr class="info">
						        <th>File name</th>
						        <th><i class="fa fa-file-code-o"></i> Standards</th>
						        <th>Actions</th>
						      </tr>
						    </thead>
						    <tbody>
						     <!-- Td will be generated by upload.js-->
						    </tbody>
				         </table>
				         <div class="text-center"><label for="download"><button id="download-button-xml" class="btn btn-primary btn-sm btn-download" disabled> Download</button> </label> <input style="display: none;" class="input-dl" name="download-button"></input></div>	
				     </form>
				 </div>
			  
			   
			    <div id="xml2rdf" class="tab-pane fade">
			   		<form action="SrvMain" method="post"  enctype="multipart/form-data">
				    	<br>
				     	<div class='input-group input-file input-file-2rdf'>
					    		 <label class='btn btn-sm btn-primary btn-upload'>
					    			Browse files...<input style='display: none;' class="input-file" name="filesToUpload[]" id="filesToUpload" type="file" accept=".xml" multiple>
					    		 </label>
				    		 </div>
				         <table class="table  table-upload table-2rdf table-striped">
						    <thead>
						      <tr class="info">
						        <th>File name</th>
						        <th><i class="fa fa-object-group"></i> LinkedMDR</th>
						        <th>Actions</th>
						      </tr>
						    </thead>
						    <tbody>
						     <!-- Td will be generated by upload.js-->
						    </tbody>
				         </table>
				         <div class="text-center"><label for="download"><button id="download-button-linkedmdr" class="btn btn-primary btn-sm btn-download" disabled> Download</button> </label> <input style="display: none;" class="input-dl" name="download-button"></input></div>	
			         </form>
			    </div>
			 </div>
         </div>
	</div>
</div>

